[workspace]
authors = ["Oliverio Starosta <oliveriostarosta@gmail.com>"]
channels = ["conda-forge"]
name = "dyscolab-tutorials"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
update-dependencies = "pixi run python set_dependencies.py"

[tasks.open]
args = [{ "arg" = "path", "default" = "" }]
cmd = "marimo edit --no-sandbox {{path}}"

[environments]
default = ["pypi"]
local = ["local"]

[dependencies]
numpy = ">=2.4.2"
matplotlib = "*"
ipykernel = "*"
ipywidgets = "*"
marimo = ">=0.20.2"
pyzmq = ">=27.1.0"
seaborn = "*"

[pypi-dependencies]
rebop = "*"

[feature.pypi.pypi-dependencies]
symbolite = ">=1.1.0"
poincare = ">=1.0.0b3"
simbio = ">= 1.0.1"

[feature.local.pypi-dependencies]
# symbolite = { path = "../u2602/symbolite", editable = true }
# poincare = { path = "../u2602/poincare", editable = true }
# simbio = { path = "../u2602/simbio", editable = true }
